INSERT INTO user_info VALUES ('Jeff Gan', 'MaNameJeff', 			'94837484', 'myemailjeff@gmail.com', 	'jeffrocks96', 'true');
INSERT INTO user_info VALUES ('Lin Jun Jie', 'ljj1996', 		'98989898', 'LJJ1996@hotmail.com', 		'ljunjie1', 'false');
INSERT INTO user_info VALUES ('Tan Ah Beng', 'ahbengbeng', 		'97776666', 'woshiahbeng@hotmail.com', 	'cutebeng99', 'false');
INSERT INTO user_info VALUES ('Johnny English', 'mrBean', 		'84572932', 'britishspy@gmail.com', 	'bestspy007', 'false');
INSERT INTO user_info VALUES ('Tan Gugu', 'guguTan', 			'23876436', 'waitlonglong@hotmail.com', 'gugu8888', 'false');
INSERT INTO user_info VALUES ('Lim Ah Seng', 'LimAS', 			'98989899', 'ahsenglim@gmail.com', 		'cookies123', 'false');
INSERT INTO user_info VALUES ('Gurmit Singh', 'Gurmit10', 		'23645634', 'gurmitsingh@yahoo.com', 	'bestinbatam', 'false');
INSERT INTO user_info VALUES ('Johnny Bravo', 'BRAVOBRAVO', 	'77776887', 'bigmuscles@hotmail.com', 	'johnnybest', 'false');
INSERT INTO user_info VALUES ('Tay Jin Gao', 'SmartBoi', 		'84844784', 'smartyjingao@hotmail.com', 'cap5ftw', 'false');
INSERT INTO user_info VALUES ('Jinny Jin', 'JinJinJin', 		'79797989', 'jinny@gmail.com', 			'rabbitscute98', 'false');
INSERT INTO user_info VALUES ('Kumar Marku', 'Kumarrr', 		'84577349', 'kumarmar@yahoo.com.sg', 	'bollybolly', 'false');
INSERT INTO user_info VALUES ('John Cena', 'JohnCenaaaaaa',		'98787878', 'itsjohncena@gmail.com', 	'youdontseeme', 'false');
INSERT INTO user_info VALUES ('Dwayne Johnson', 'TheRock', 		'91023038', 'dwaynetherock@hotmail.com', 'richandfamous', 'false');
INSERT INTO user_info VALUES ('Sim Ah Lian', 'AhLianChiobu',	'93104034', 'chiobu@gmail.com', 		'hotgirl444', 'false');
INSERT INTO user_info VALUES ('Benny Long', 'Benny', 			'98430241', 'bennyl@gmail.com', 		'benbenboi10', 'false');
INSERT INTO user_info VALUES ('Scarlett Johansson', 'Widow',	'84648390', 'blackwindow@hotmail.com', 	'blackwidowrox', 'false');
INSERT INTO user_info VALUES ('Jennifer Lawrence', 'Katniss', 	'84734894', 'jenniferlawrence@gmail.com', 'everdeen1', 'false');
INSERT INTO user_info VALUES ('Michael Jackson', 'rockNroll', 	'96969691', 'kingofpop@gmail.com', 		'mjackson', 'false');
INSERT INTO user_info VALUES ('Harry Potter', 'magicboy95', 	'95454538', 'potterh@gmail.com', 		'darkarts999', 'false');
INSERT INTO user_info VALUES ('Denial Redcliff', 'noobPotter', 	'94733332', 'danielradcliffe@hotmail.com', 'famousandrich', 'false');
INSERT INTO user_info VALUES ('Prad Bitt', 'fakeBradPitt', 		'87372933', 'pradbitt@gmail.com', 		'bradpittxxxx', 'false');
INSERT INTO user_info VALUES ('Harrison Ford', 'HanSolo', 		'90033283', 'swhansolo@yahoo.com', 		'hansoloford1', 'false');
INSERT INTO user_info VALUES ('Leonardo DiCaprio', 'Leonardo', 	'38484394', 'leonardo@gmail.com', 		'wolfwallstreet', 'false');
INSERT INTO user_info VALUES ('Gal Gadot', 'Wonderwoman', 		'93800409', 'galgadot@gmail.com', 		'wonderw999', 'false');
INSERT INTO user_info VALUES ('Christian Bale', 'BatmanBale', 	'93477743', 'imbatman@gmail.com', 		'batmanrocks', 'false');
INSERT INTO user_info VALUES ('Jeevan NeeralaName', 'Jeevan', 	'94831484', 'jeevancool@gmail.com', 	'imsocool96', 'true');
INSERT INTO user_info VALUES ('Zhi Thon', 'Zhit', 		'32456434', 'tehzhithon@gmail.com', 'imthecoolest', 'true');
INSERT INTO user_info VALUES ('Wee Keong', 'OWK', 		'98765431', 'ongweekeong@gmail.com', 'password', 'true');